func getgems() {    
    collectGem()
    moveForward()
    collectGem()
    moveForward()
    collectGem()
    turnRight()
    moveForward()
    collectGem()
    turnRight()
    moveForward()
    collectGem()
    moveForward()
    collectGem()
    turnLeft()
    moveForward()
    collectGem()
    turnLeft()
    moveForward()
    collectGem()
    moveForward()
    collectGem()
}

getgems()
